Docstore.App/Models/Forms/FolderForm.cs
using System.ComponentModel.DataAnnotations;

namespace Docstore.App.Models.Forms
{
    public class FolderForm
    {
        public string? Name { get; set; }

        [DataType(DataType.MultilineText)]
        public string? Description { get; set; }
    }
}

Docstore.App/Controllers/Api/FoldersController.cs
using AutoMapper;
using Docstore.App.Common.Extendeds;
using Docstore.App.Models.Forms;
using Docstore.Application.Interfaces;
using Docstore.Application.Models.DTO;
using Docstore.Domain.Entities;
using Docstore.Persistence.Contexts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Docstore.App.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize]
    public class FoldersController : ExtendedControllerBase
    {
        private readonly ILogger<FoldersController> _logger;
        private readonly IMapper _mapper;
        private readonly IFolderRepository _folderRepository;
        private readonly ApplicationDbContext _context;

        public FoldersController(IMapper mapper, IFolderRepository folderRepository, ApplicationDbContext context, ILogger<FoldersController> logger)
        {
            _folderRepository = folderRepository;
            _mapper = mapper;
            _context = context;
            _logger = logger;
        }


        #region actions
        [HttpGet]
        public async Task<ActionResult<IEnumerable<GetFolderDto>>> Get(string? search = null)
        {
            if (string.IsNullOrWhiteSpace(search))
                return new List<GetFolderDto>();

            var folders = await _folderRepository.SearchAsync(UserId, search);
            var dto = _mapper.Map<IEnumerable<GetFolderDto>>(folders);

            return dto.ToList();
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<GetFolderDto>> Get(int id)
        {
            var folder = await _folderRepository.FindByIdAsync(UserId, id);

            if(folder == null)
                return NotFound();

            var dto = _mapper.Map<GetFolderDto>(folder);
            return dto;
        }

        [HttpPost]
        public async Task<ActionResult<Folder>> Post([FromBody] FolderForm form)
        {
            // model validation
            try
            {
                if (ModelState.IsValid && form != null)
                {
                    // transform to database entity
                    var folder = _mapper.Map<Folder>(form);
                    folder.UserId = UserId;

                    // save in database
                    await _folderRepository.AddAsync(folder);
                    await _context.SaveChangesAsync();

                    // response
                    return CreatedAtAction(nameof(Get), new { id = folder.Id }, folder);  
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"{nameof(Post)}:{nameof(FoldersController)}");
                ModelState.AddModelError("", "An unexpected error occurred.");
            }

            // is not supposed to get here
            return StatusCode(StatusCodes.Status500InternalServerError);
        }
        #endregion
    }
}

Docstore.App/Controllers/DocumentsController.cs
using AutoMapper;
using Docstore.App.Common.Extendeds;
using Docstore.App.Common.Extensions;
using Docstore.App.Models;
using Docstore.App.Models.Abstracts;
using Docstore.App.Models.Forms;
using Docstore.Application.Common;
using Docstore.Application.Extensions;
using Docstore.Application.Interfaces;
using Docstore.Application.Models;
using Docstore.Application.Models.DTO;
using Docstore.Domain.Entities;
using Docstore.Domain.Extensions;
using Docstore.Persistence.Contexts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace Docstore.App.Controllers
{
    [Authorize]
    public class DocumentsController : ExtendedController
    {
        private const int PAGE_SIZE = 6;

        private readonly ILogger<DocumentsController> _logger;
        private readonly IMapper _mapper;
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly AppSettings _appSettings;
        private readonly IDocumentRepository _documentRepository;
        private readonly IFolderRepository _folderRepository;
        private readonly IDocumentFileRepository _documentFileRepository;

        public DocumentsController(ILogger<DocumentsController> logger, ApplicationDbContext db, IMapper mapper, IWebHostEnvironment hostingEnvironment, IOptions<AppSettings> appSettings, IDocumentRepository documentRepository, IFolderRepository folderRepository, IDocumentFileRepository documentFileRepository)
        {
            _logger = logger;
            _db = db;
            _mapper = mapper;
            _hostingEnvironment = hostingEnvironment;
            _appSettings = appSettings.Value;
            _documentRepository = documentRepository;
            _folderRepository = folderRepository;
            _documentFileRepository = documentFileRepository;
        }


        #region actions
        public async Task<IActionResult> Index(int? page = 1, int? folderId = null, int? tagId = null)
        {
            // get data
            var documents = await _documentRepository.GetPagedReponseAsync(UserId, page ?? 1, PAGE_SIZE, tag: tagId, folder: folderId);

            Folder? folder = null;
            if (folderId != null)
                folder = await _folderRepository.FindByIdAsync(UserId, folderId.Value);

            // response
            var viewModel = new DocumentsIndexViewModel
            {
                Documents = documents,
                FolderId = folderId,
                Folder = folder
            };
            return View(viewModel);
        }

        public async Task<IActionResult> Create(int? folderId = null)
        {
            // data
            Folder? folder = null;

            if (folderId != null)
                folder = await _folderRepository.FindByIdAsync(UserId, folderId.Value);

            // response
            var viewModel = new DocumentCreateViewModel(folderId, folder);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DocumentForm? form)
        {
            // model validation
            try
            {
                if (ModelState.IsValid && form != null)
                {
                    var documentFiles = await _documentFileRepository.FindByIdsAsync(UserId, form.Files.ToArray());

                    // transform to database entity
                    var document = _mapper.Map<Document>(form);
                    document.Tags = await form.CreateNewTagsAndGetListAsync(_db, UserId);
                    document.Files = documentFiles.ToList();
                    document.UserId = UserId;

                    foreach (var (item, index) in document.Files.WithIndex())
                        item.Order = index;

                    // save in database
                    await _documentRepository.AddAsync(document, save: true);

                    // response
                    return RedirectToAction(nameof(Index))
                        .AddToast(TempData, ToastType.Success, $"\"{document.Name}\" successfuly created!");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"{nameof(Create)}:{nameof(DocumentsController)}");
                ModelState.AddModelError("", "An unexpected error occurred.");
            }

            // pick folder if it selected
            Folder? folder = null;
            if (form?.FolderId != null)
                folder = await _folderRepository.FindByIdAsync(UserId, form.FolderId.Value);

            IEnumerable<GetDocumentFileDto> files = new List<GetDocumentFileDto>();
            if (form?.Files != null && form.Files.Any())
            {
                var documentFiles = await _documentFileRepository.FindByIdsAsync(UserId, form.Files.ToArray());
                files = _mapper.Map<IEnumerable<GetDocumentFileDto>>(documentFiles);
            }

            // response
            var viewModel = new DocumentCreateViewModel(folder?.Id, folder, files)
            {
                Form = form ?? DocumentFormViewModel.GetDefaultFormValues()
            };
            return View(viewModel);
        }


        public async Task<IActionResult> Show(int id)
        {
            var document = await _documentRepository.FindByIdWithTypeAndTagsAndFileAsync(UserId, id);

            if (document == null)
                return NotFound();

            // response
            var viewModel = new DocumentShowViewModel(document);
            return View(viewModel);
        }

        [HttpGet("{controller}/" + nameof(Show) + "/{id:int}/{action}/{fileId:int}")]
        public async Task<IActionResult> Download(int id, int fileId)
        {
            var file = await _documentFileRepository.FindByIdAsync(UserId, fileId);

            if (file == null || file.DocumentId != id)
                return NotFound();

            // response
            var filePath = file.GetFilePath(_hostingEnvironment.ContentRootPath);
            return File(await Encryption.DecryptWithMemoryAsync(filePath, _appSettings.AppKey!), file.MimeType!, file.GetFileName(), true);
        }

        public async Task<IActionResult> Edit(int id)
        {
            // check if exist
            var document = await _documentRepository.FindByIdAsync(UserId, id);
            if (document == null)
                return RedirectToAction(nameof(Index))
                    .AddToast(TempData, ToastType.Error, "This document does not exist.");

            return EditDefault(document);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, DocumentForm? form)
        {
            var document = await _documentRepository.FindByIdAsync(UserId, id);

            if (document == null)
                return NotFound();

            // model validation
            try
            {
                if (ModelState.IsValid && form != null)
                {
                    var documentFiles = await _documentFileRepository.FindByIdsAsync(UserId, form.Files.ToArray());

                    // copie new data in entity
                    _mapper.Map(form, document);

                    document.Tags = await form.CreateNewTagsAndGetListAsync(_db, UserId);
                    document.Files = documentFiles.ToList();

                    // save in database
                    await _documentRepository.UpdateAsync(document, save: true);

                    // response
                    return RedirectToAction(nameof(Index))
                        .AddToast(TempData, ToastType.Success, $"\"{document.Name}\" successfuly updated!");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"{nameof(Create)}:{nameof(DocumentsController)}");
                ModelState.AddModelError("", "An unexpected error occurred.");
            }

            return EditDefault(document);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var document = await _documentRepository.FindByIdWithTypeAndTagsAndFileAsync(UserId, id);

            if (document == null)
                return NotFound();

            // delete
            foreach (var item in document.Files)
                await _documentFileRepository.DeleteAsync(item);
            await _documentRepository.DeleteAsync(document, save: true);

            return RedirectToAction(nameof(Index))
                .AddToast(TempData, ToastType.Success, $"\"{document.Name}\" has been deleted!");
        }
        #endregion

        #region privates
        private IActionResult EditDefault(Document document)
        {
            // data
            var form = _mapper.Map<DocumentForm>(document);
            form.Tags = document.Tags.Select(x => x.Name!);
            var files = _mapper.Map<IEnumerable<GetDocumentFileDto>>(document.Files);

            // response
            var viewModel = new DocumentEditViewModel(document.FolderId, document.Folder, files)
            {
                Form = form
            };
            return View(viewModel);
        }
        #endregion
    }
}

Docstore.App/Views/Folders/Partials/_CreateModal.cshtml
@model Docstore.App.Models.Forms.FolderForm

@{
    ViewData.TemplateInfo.HtmlFieldPrefix = "Form";
}

<div x-data="Modal" x-on:keydown.window.escape="open = false" x-show="open" class="fixed z-50 inset-0 overflow-y-auto" aria-labelledby="modal-title" x-ref="dialog" aria-modal="true">
    <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0" x-on:modal-ex.window="open = !open">

        <div x-show="open" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" x-description="Background overlay, show/hide based on modal state." class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" x-on:click="open = false" aria-hidden="true">
        </div>

        <!-- This element is to trick the browser into centering the modal contents. -->
        <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">​</span>

        <form x-show="open" x-data="FormFolderCreate('@ViewData.TemplateInfo.HtmlFieldPrefix')" x-ref="form" x-on:submit.prevent="submit" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100 translate-y-0 sm:scale-100" x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" x-description="Modal panel, show/hide based on modal state." class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full"
              method="post" enctype="multipart/form-data" up-target="[layout-form]" up-fail-target="[layout-form-modal]" layout-form-modal up-active>

            <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4 dark:bg-gray-900">
                <div class="flex items-start">

                    <div class="space-y-6 w-full">
                        <div asp-validation-summary="ModelOnly"></div>

                        <div>
                            <label class="block text-sm font-medium text-gray-700 dark:text-gray-500" asp-errors-class="text-red-700 dark:text-red-500" asp-for="Name">Name</label>
                            <input      asp-for="Name" type="text" class="mt-1 block w-full shadow-sm sm:text-sm rounded-md border-none focus:ring-2" asp-valid-class="focus:ring-primary-500 bg-gray-50 dark:bg-gray-800 text-black dark:text-gray-100" asp-errors-class="text-red-900 placeholder-red-700 focus:ring-red-500 dark:bg-red-100" />
                            <p class="mt-1 text-sm text-red-600 dark:text-red-500 hidden"><span class="font-medium">Oops!</span> <span class="field-validation" asp-validation-for="Name"></span></p>
                        </div>
                        <div>
                            <label class="block text-sm font-medium text-gray-700 dark:text-gray-500" asp-errors-class="text-red-700 dark:text-red-500" asp-for="Description">Description <small class="text-xs italic">(optional)</small></label>
                            <textarea asp-for="Description" class="mt-1 block w-full shadow-sm sm:text-sm rounded-md border-none focus:ring-2" asp-valid-class="focus:ring-primary-500 bg-gray-50 dark:bg-gray-800 text-black dark:text-gray-100" asp-errors-class="text-red-900 placeholder-red-700 focus:ring-red-500 dark:bg-red-100"></textarea>
                            <p class="mt-1 text-sm text-red-600 dark:text-red-500 hidden"><span class="font-medium">Oops!</span> <span class="field-validation" asp-validation-for="Description"></span></p>
                        </div>
                    </div>

                </div>
            </div>
            <div class="bg-gray-50 dark:bg-black px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
                <button type="submit" class="ml-auto py-2 px-3 bg-primary-500 text-primary-900 hover:text-white text-sm font-semibold rounded-md shadow-lg shadow-primary-500/10 hover:shadow-primary-500/50 active:shadow-primary-500/75 focus:outline-none transition duration-500">Submit</button>
                <button type="button" class="py-2 px-3 text-gray-500 hover:text-gray-700 dark:hover:text-gray-100 text-sm font-semibold rounded-md transition duration-500" x-on:click="open = false">
                    Cancel
                </button>
            </div>
        </form>

    </div>
</div>

Docstore.App/Views/Folders/Partials/_Form.cshtml
@model FolderFormViewModel

<form method="post" enctype="multipart/form-data" up-target="[layout-form]" layout-form up-scroll="false">
    <div class="px-4 py-5 bg-white dark:bg-gray-900 space-y-6 sm:p-6">
        <div class="text-red-500 text-xs" asp-validation-summary="ModelOnly"></div>

        <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-500" asp-errors-class="text-red-700 dark:text-red-500" asp-for="Form.Name">Name</label>
            <input autofocus asp-for="Form.Name" type="text" class="mt-1 block w-full shadow-sm sm:text-sm rounded-md border-none focus:ring-2" asp-valid-class="focus:ring-primary-500 bg-gray-50 dark:bg-gray-800 text-black dark:text-gray-100" asp-errors-class="text-red-900 placeholder-red-700 focus:ring-red-500 dark:bg-red-100" />
            <p asp-display-validation-for="Form.Name" class="mt-1 text-sm text-red-600 dark:text-red-500"><span class="font-medium">Oops!</span> <span asp-validation-for="Form.Name"></span></p>
        </div>

        <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-500" asp-errors-class="text-red-700 dark:text-red-500" asp-for="Form.Description">Description <small class="text-xs italic">(optional)</small></label>
            <textarea asp-for="Form.Description" class="mt-1 block w-full shadow-sm sm:text-sm rounded-md border-none focus:ring-2" asp-valid-class="focus:ring-primary-500 bg-gray-50 dark:bg-gray-800 text-black dark:text-gray-100" asp-errors-class="text-red-900 placeholder-red-700 focus:ring-red-500 dark:bg-red-100"></textarea>
            <p asp-display-validation-for="Form.Description" class="mt-2 text-sm text-red-600 dark:text-red-500"><span class="font-medium">Oops!</span> <span asp-validation-for="Form.Description"></span></p>
        </div>

    </div>
    <div class="px-4 py-3 bg-gray-50 dark:bg-black sm:px-6">
        <div class="flex">
            <a up-target="[layout-main]" up-preload asp-action="Index" class="py-2 px-3 text-gray-500 hover:text-gray-700 dark:hover:text-gray-100 text-sm font-semibold rounded-md transition duration-500">Cancel</a>
            <button type="submit" class="ml-auto py-2 px-3 bg-primary-500 text-primary-900 hover:text-white text-sm font-semibold rounded-md shadow-lg shadow-primary-500/10 hover:shadow-primary-500/50 active:shadow-primary-500/75 focus:outline-none transition duration-500">Submit</button>
        </div>
    </div>
</form>

Docstore.App/Views/Folders/Partials/_ShowInformations.cshtml
@using Humanizer
@using Docstore.Domain.Entities
@model Folder

@if (Model == null) return;

<div class="divide-y divide-solid divide-black">
    <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <div class="text-sm font-medium text-gray-500">
            Name
        </div>
        <div class="mt-1 text-sm text-gray-100 sm:mt-0 sm:col-span-2">
            @Model.Name
        </div>
    </div>

    <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <div class="text-sm font-medium text-gray-500">
            Description
        </div>
        <div class="mt-1 text-sm text-gray-100 sm:mt-0 sm:col-span-2">
            @if (!string.IsNullOrWhiteSpace(Model.Description))
            {
                <span>@Model.Description</span>
            }
            else
            {

                <i class="italic text-xs text-gray-500">no description</i>
            }
        </div>
    </div>

    <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <div class="text-sm font-medium text-gray-500">
            Total Size
        </div>
        <div class="mt-1 text-sm text-gray-100 sm:mt-0 sm:col-span-2">
            @Model.Size.Bytes()
            <span class="italic text-xs">(<a asp-action="Index" asp-controller="Documents" asp-route-folderId="@Model.Id" class="text-primary-600 hover:text-primary-500 active:text-primary-400">@("document".ToQuantity(@Model.DocumentsCount))</a>)</span>
        </div>
    </div>

    <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <div class="text-sm font-medium text-gray-500">
            Creation Date
        </div>
        <div class="mt-1 text-sm text-gray-100 sm:mt-0 sm:col-span-2">
            <span>@Model.CreatedAt.Humanize()</span>
        </div>
    </div>

    <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <div class="text-sm font-medium text-gray-500">
            Update Date
        </div>
        <div class="mt-1 text-sm text-gray-100 sm:mt-0 sm:col-span-2">
            <span>@Model.UpdatedAt.Humanize()</span>
        </div>
    </div>
</div>

Docstore.App/Views/Folders/Partials/_Table.cshtml
@using Docstore.Application.Models
@using Humanizer
@using Docstore.Domain.Entities
@model PagedResult<Folder>

<div class="flex flex-col" layout-table>
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
            <div class="shadow overflow-hidden border-b border-gray-200 dark:border-gray-800 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-800">
                    <thead class="bg-gray-50 dark:bg-black">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider hidden sm:table-cell">
                                Size
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Last updated
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Edit</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
                        @if (Model != null && Model.Results.Any())
                        {
                            @foreach (var item in Model.Results)
                            {
                                <tr>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <div class="flex items-center">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-7 w-7 text-primary-400" viewBox="0 0 20 20" fill="currentColor"><path d="M2 6a2 2 0 012-2h5l2 2h5a2 2 0 012 2v6a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" /></svg>
                                            <div class="ml-4">
                                                <div class="text-sm font-medium text-gray-900 dark:text-gray-300 truncate">
                                                    @item.Name
                                                </div>
                                                @if (!string.IsNullOrWhiteSpace(item.Description))
                                                {
                                                    <div class="text-sm text-gray-500 dark:text-gray-600 truncate">
                                                        @item.Description!.Truncate(20)
                                                    </div>
                                                }
                                            </div>
                                        </div>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-gray-900 dark:text-gray-300 hidden sm:table-cell">
                                        @item.Size.Bytes()
                                        <span class="italic text-xs">(@("document".ToQuantity(@item.DocumentsCount)))</span>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-gray-900 dark:text-gray-300 text-sm sm:text-base">
                                        @item.UpdatedAt.Humanize()
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a up-target="[layout-main]" asp-action="Show" asp-controller="Folders" asp-route-id="@item.Id" class="text-primary-600 hover:text-primary-500 active:text-primary-400">Details</a>
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="10" class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 text-center">
                                    no Folders
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                <partial name="~/Views/Shared/Partials/_Pagination.cshtml" model="@Model?.Pagination" />
            </div>
        </div>
    </div>
</div>